# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRWrZuQiYWBDkEMU_KT07uDwMZbunja_
"""

import numpy as np
import matplotlib.pyplot as plt
import pywt
from scipy.signal import find_peaks

ecg_signals = np.genfromtxt("ECG_reposo.txt", delimiter="\t",skip_header = 3, missing_values= 0)
# Extraemos la columna de la señal
chn = 5
ecg_signal = ecg_signals[:, chn]
ecg_signal = ecg_signal - np.mean(ecg_signal)
Fs_ecg = 360
Ts_ecg = 1/Fs_ecg
n_ecg= len(ecg_signal)
t_ecg = np.arange(0,n_ecg*Ts_ecg,Ts_ecg)

"""## Ploteamos las señales sin filtrar

## Ploteamos las señales sin filtrar
"""
plt.figure(figsize=(11, 5))
plt.xlim(10,20)
plt.plot(t_ecg, ecg_signal, label="señal")
plt.xlabel("Tiempo (s)")
plt.ylabel("Amplitud")
plt.legend(loc="upper right")
plt.title("Señal ECG Reposo - Original")
plt.show()

n_level = 2
ecg_coeffs = pywt.wavedec(ecg_signal, 'sym3', level=n_level)

threshold = 1
ecg_coeffs_thresh = [pywt.threshold(c, threshold, mode='soft') for c in ecg_coeffs]

filtered_ecg_signal = pywt.waverec(ecg_coeffs_thresh, 'sym3')

plt.figure(figsize=(11, 5))
plt.plot(t_ecg, filtered_ecg_signal)
plt.xlim(10,20)
plt.title('Señal ECG Reposo - filtrada')
plt.xlabel("Tiempo (s)")
plt.ylabel("Amplitud")
plt.tight_layout()
plt.show()